<?php
/**
 * Created by PhpStorm.
 * User: ADMIN
 * Date: 28/03/2018
 * Time: 21:08
 */

namespace ProduitBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function GetUserNameDQL($id){
        $q = $this->getEntityManager()
            ->createQuery('SELECT u FROM PidevBundle:USER u WHERE p.id=:id')
            ->setParameter('id', $id);
        return $q->getResult();


    }

}